### PR TITLE
The footer section is moved towards the right

### PR DESCRIPTION
**Pull request by dipankurverma**

### CODE REVIEW

**Comment by sunami09** [comment]
@dipankurverma would you like to join this organization?

**Review by sunami09 — CHANGES_REQUESTED** [review]
@dipankurverma don't use float, try text-align: end, as the content will be given some padding later, try using less hard coding if possible.

**Comment by dipankurverma** [comment]
@sunami09 I mean yeah , sure

**Comment by sunami09** [comment]
@dipankurverma check your email and join. Welcome to our team!!
I reviewed your code and I provided some suggestions kindly look into it.

**Comment by dipankurverma** [comment]
@sunami09 Ok I'll  do the changes and thanks for assigning  me for it.

**Comment by sunami09** [comment]
@dipankurverma very good!! try to solve other issues, I will merge this PR

**Pull request merged**
